modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://legacy.curseforge.com/minecraft/mc-mods/verity-je/settings/issues"
showAsResourcePack=false
logoFile="icon.png"

[[mods]]
modId="verity"
version="5.7.4"
displayName="Verity Forge"
logoFile="logo.png"
authors="Varmite, ThatMob (Creator of Verity), BlockMaster29, JJack"
description='''Hello, I'm Verity! Your personal helper friend. You can ask me anything, I know everything.'''

[[dependencies.verity]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.verity]]
modId="yet_another_config_lib_v3"
mandatory=true
versionRange="[3.6,)"
ordering="NONE"
side="CLIENT"

[[dependencies.verity]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

# This tells Forge that your mod requires GeckoLib to launch
[[dependencies.verity]]
modId="geckolib"
mandatory=true
versionRange="[4.4,)"
ordering="NONE"
side="BOTH"