name: Build

on:
  push:
    branches: [ "main", "master", "old" ]
  pull_request:
    branches: [ "main", "master", "old" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: verity-mod
          path: build/libs/*.jar
          if-no-files-found: error
